name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  markdown_widget:
    path: ../
  easy_model: ^1.0.0

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^5.4.2

flutter:

  uses-material-design: true

  assets:
    - assets/